# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine

# copy WAR into image
COPY demo.war /demo.war
 
# run application with this command line 
CMD ["catalina.sh", "-Dspring.profiles.active=default", "/demo.war"]